desktop (arm64, x64, and x86) binaries need to be packed in a fat framworks building XCFramworks
jizoquval/multiplatform-swiftpackage pull request #2
Opened 2022-04-29 04:12 UTC by luca992

With your pr, I'm running into this issue: https://developer.apple.com/forums/thread/666335

Before making an XCFramwork: macos desktop (including simulators) arm64, x64, and x86 binaries need to be packed in a fat frameworks before building the XCFramworks

2022-04-29 21:01 UTC, jizoquval requested changes
@luca992 Greater job! I added a few comments which may make it better. 

Also I had some troubles with publish plugin to maven local using gradle 7.4.2. 
Execution failed for task ':processResources'.

 > Entry META-INF/gradle-plugins/com.chromaticnoise.multiplatform-swiftpackage.properties is a duplicate but no duplicate handling strategy has been set.

Do you have the same troubles?

2022-04-29 21:01 UTC, jizoquval commented on src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt
> +            destinationDir = buildDir.resolve("bin/iosSimulatorUniversal/${buildType}Framework")
I believe what you also need to provide **baseName**. If packageName is different from **shared**, an exception will be thrown. I think we can get it from configuration:
`baseName = configuration.packageName.value`

2022-04-29 21:01 UTC, jizoquval commented on src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt
> +            from(targets.map { it.framework!! } )
Please use `.mapNotNull { ... }` instead of `!!`

2022-04-29 21:01 UTC, jizoquval commented on src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt
> +            destinationDir = buildDir.resolve("bin/iosSimulatorUniversal/${buildType}Framework")
Same for `registerCreateUniversalWatchosSimulatorFrameworkTask()` and `registerCreateUniversalTvosSimulatorFrameworkTask()`

2022-04-29 21:01 UTC, jizoquval commented on src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt
> +            from(targets.map { it.framework!! } )
Same for registerCreateUniversalWatchosSimulatorFrameworkTask() and registerCreateUniversalTvosSimulatorFrameworkTask()

2022-04-29 21:01 UTC, jizoquval commented on src/main/kotlin/com/chromaticnoise/multiplatformswiftpackage/task/CreateXCFrameworkTask.kt
> +        onlyIf{ getTvosSimulatorFrameworks(configuration).size > 1 }
Please format code in entire file

2022-04-30 18:25 UTC, luca992 commented
> @luca992 Greater job! I added a few comments which may make it better.
> 
> Also I had some troubles with publish plugin to maven local using gradle 7.4.2. Execution failed for task ':processResources'.
> 
> > Entry META-INF/gradle-plugins/com.chromaticnoise.multiplatform-swiftpackage.properties is a duplicate but no duplicate handling strategy has been set.
> 
> Do you have the same troubles?

Yeah, I see that now. I think it's releated to: https://github.com/gradle/gradle/issues/17236

I included a fix

2022-04-30 18:30 UTC, luca992 commented
However, I still get the warning: 
```
Multiple publications with coordinates 'com.chromaticnoise.multiplatform-swiftpackage:com.chromaticnoise.multiplatform-swiftpackage.gradle.plugin:2.0.3' are published to repository 'mavenLocal'. The publications 'pluginMaven' in root project 'multiplatform-swiftpackage' and 'pluginMavenPluginMarkerMaven' in root project 'multiplatform-swiftpackage' will overwrite each other!
```
 when publishing to maven local. But no error now.

2022-05-01 11:59 UTC, merged